version: "3.8"
services:
  fastcash-db:
    build: 
      dockerfile: ./Dockerfiles/db.dockerfile
      context: .
    container_name: fastcash-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "${APP_DB_PORT:-5442}:5432"
    volumes:
      - "${POSTGRES_DATA_DIR:-/opt/fastcash/data/postgres}:/var/lib/postgresql/data"
      - "${POSTGRES_BACKUP_DIR:-/opt/fastcash/backup}:/project/backup"