version: "3.8"
services:
  fastcash-backend:
    build:
      dockerfile: ./Dockerfiles/app.dockerfile
      context: .
    container_name: fastcash-backend
    env_file:
      - .env
    restart: always
    environment:
      EMAIL: "pythonbiellagroup@gmail.com"
      DEBUG_MODE: ${APP_DEBUG_MODE}
      VERBOSITY: ${APP_VERBOSITY}
      API_SECRET_KEY: ${APP_SECRET_KEY}
      API_ENDPOINT_PORT: ${APP_ENDPOINT_PORT}
      DB_NAME: ${APP_DB_NAME}
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_PORT: ${APP_DB_PORT}
      DB_HOST: ${APP_DB_HOST}
    depends_on:
      - fastcash-db
    ports:
      - "${APP_DOCKER_PORT:-8044}:${APP_ENDPOINT_PORT:-8000}"
  
  fastcash-db:
    build: 
      dockerfile: ./Dockerfiles/db.dockerfile
      context: .
    container_name: fastcash-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "${APP_DB_PORT:-5442}:5432"
    volumes:
      - "${POSTGRES_DATA_DIR:-/opt/fastcash/data/postgres}:/var/lib/postgresql/data"
      - "${POSTGRES_BACKUP_DIR:-/opt/fastcash/backup}:/project/backup"